# Generated by Django 3.0.4 on 2020-04-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='rgba(255, 255, 255, 1)', max_length=20, verbose_name='背景颜色')),
                ('name', models.CharField(max_length=20, verbose_name='区域')),
            ],
        ),
    ]
