# Generated by Django 3.0.4 on 2020-04-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundsettings',
            name='color',
            field=models.CharField(default='rgba(255, 255, 255, 1)', max_length=50, verbose_name='背景颜色'),
        ),
        migrations.AlterField(
            model_name='backgroundsettings',
            name='name',
            field=models.CharField(max_length=50, verbose_name='区域'),
        ),
    ]
