# Generated by Django 3.0.4 on 2020-04-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200403_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsettings',
            name='code',
            field=models.IntegerField(default=1, verbose_name='代号'),
        ),
    ]
