# Generated by Django 3.0.4 on 2020-03-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('company', '公司'), ('department', '部门')], default='company', max_length=20)),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Organization')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Organization')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role')),
                ('superior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
            options={
                'db_table': 'user_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=158)),
                ('sort', models.IntegerField(blank=True)),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['id'],
            },
        ),
    ]
