# Generated by Django 3.0.4 on 2020-03-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200317_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='pid',
        ),
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=100, verbose_name='链接地址'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.Menu', verbose_name='父级菜单'),
        ),
    ]
