# Generated by Django 3.0.4 on 2020-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20200317_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, help_text='如果有子菜单，不需要填写该字段', max_length=100, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
