# Generated by Django 3.0.4 on 2020-03-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200316_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='superior',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
