# Generated by Django 3.0.4 on 2020-03-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_userinfo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.Role', verbose_name='角色'),
        ),
    ]
